### ISSUE TITLE
[Bug]S3 API Multipart Uploads with 0 Bytes

### ISSUE THREAD

**Issue by jerebear12** [seaweedfs/seaweedfs#3660]
**Describe the bug**
Multipart Uploads using the S3 API fail at the completion step. I am using the JavaScript SDK V3 with Typescript. Parts are visible in the Filer UI as they are sent but as soon as the CompleteMultipartUpload command is sent, the parts in the .uploads folder disappear(I believe this is expected behavior) and the file looks like it is added to the bucket folder, but it has a value of 0 bytes. Files shown with byte values other than 0 were uploaded without using the Multipart Upload command.
![filer-ui](https://user-images.githubusercontent.com/72420925/189993475-3daa9f25-1ee5-4589-a4d8-83a7369567c0.JPG)

**System Setup**
Set up from Getting Started in the Wiki. 
Version 3.23 running on Ubuntu VM
1 Master 1 Filer(with S3 gateway) 1 Volume Server 8 Volumes

**Expected behavior**
The file parts should disappear from the temporary .uploads folder, and the file should be created with all data in the bucket folder. Length in bytes should accurately reflect file size, and the file should open and display its contents as expected.

**Steps to reproduce**
I made a small repo that has all the files needed to reproduce the error. You will need a an instance of seaweed running with the S3 gateway enabled as well.

https://github.com/jerebear12/s3-multipart-error

**Comment by betwowt** [comment]
Same problem
---
use s3 browser program
upload 1G size file 
use fuse mount watch 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/16661764/190292188-b2b924ad-9432-4162-8b1d-fddd1c2217aa.png">

**Comment by chrislusf** [comment]
@jerebear12 can you use some docker to reproduce? I have no knowledge about nodejs, and here is the output when following the readme.

```
dev/s3-multipart-error () - (main) > npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm notice
npm notice New minor version of npm available! 8.1.2 -> 8.19.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.19.2
npm notice Run npm install -g npm@8.19.2 to update!
npm notice
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/chrislu/dev/s3-multipart-error/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/chrislu/dev/s3-multipart-error/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chrislu/.npm/_logs/2022-09-15T07_34_16_835Z-debug.log
```

**Comment by chrislusf** [comment]
@jerebear12 @betwowt  this should be fixed now. Please help to confirm.

**Comment by betwowt** [comment]
@chrislusf 
fixed
<img width="647" alt="image" src="https://user-images.githubusercontent.com/16661764/190369132-fd24aa56-d5c3-4874-8cd9-48438183b508.png">

**Comment by jerebear12** [comment]
@betwowt @chrislusf 
I am still seeing the error. To test new changes, I followed these [instructions](https://github.com/seaweedfs/seaweedfs#installation-guide) and tried using the same program I had used to upload the files. The output is exactly the same on my end. 

Also, Chris, I fixed the repository with reproduction steps. I mistakenly assumed packages would work on another device. The readme is also updated with current instructions.

betwowt How are you talking to the S3 gateway?

**Comment by betwowt** [comment]
@jerebear12 
Did you restart all processes? I am using the [s3 browser](https://www.nakivo.com/blog/overview-of-amazon-s3-browser-windows/) to verify that it is ok. s3 browser will upload files larger than 8M in segments. You can use the s3 browser to verify

**Comment by chrislusf** [comment]
Could not run
```
s3-multipart-error/app () - (main) > npx snowpack dev --polyfill-node
[11:09:20] [snowpack] Welcome to Snowpack! Because this is your first time running
this project, Snowpack needs to prepare your dependencies. This is a one-time step
and the results will be cached for the lifetime of your project. Please wait...
[11:09:20] [snowpack] + @aws-sdk/client-s3@3.170.0
[11:09:22] [snowpack] └── @aws-sdk/middleware-bucket-endpoint@3.170.0
[11:09:22] [snowpack]   └── @aws-sdk/util-config-provider@3.170.0
[11:09:22] [snowpack]   └── @aws-sdk/protocol-http@3.170.0
[11:09:22] [snowpack]   └── @aws-sdk/util-arn-parser@3.170.0
[11:09:23] [snowpack] └── @aws-sdk/middleware-serde@3.170.0
[11:09:23] [snowpack] └── @aws-sdk/smithy-client@3.170.0
[11:09:23] [snowpack]   └── @aws-sdk/middleware-stack@3.170.0
[11:09:23] [snowpack] └── @aws-sdk/xml-builder@3.170.0
[11:09:23] [snowpack] └── entities@2.2.0
[11:09:24] [snowpack] └── fast-xml-parser@3.19.0
[11:09:24] [snowpack] └── @aws-sdk/middleware-sdk-s3@3.170.0
[11:09:24] [snowpack] └── @aws-sdk/middleware-ssec@3.170.0
[11:09:24] [snowpack] └── @aws-sdk/middleware-location-constraint@3.170.0
[11:09:24] [snowpack] └── @aws-sdk/middleware-flexible-checksums@3.170.0
[11:09:25] [snowpack]   └── @aws-sdk/is-array-buffer@3.170.0
[11:09:25] [snowpack]   └── @aws-crypto/crc32@2.0.0
[11:09:25] [snowpack]     └── @aws-crypto/util@2.0.2
[11:09:25] [snowpack]       └── @aws-sdk/util-utf8-browser@3.170.0
[11:09:25] [snowpack]   └── @aws-crypto/crc32c@2.0.0
[11:09:25] [snowpack] └── @aws-sdk/config-resolver@3.170.0
[11:09:25] [snowpack]   └── @aws-sdk/util-middleware@3.170.0
[11:09:26] [snowpack] └── @aws-sdk/eventstream-serde-config-resolver@3.170.0
[11:09:26] [snowpack] └── @aws-sdk/middleware-content-length@3.170.0
[11:09:26] [snowpack] └── @aws-sdk/middleware-expect-continue@3.170.0
[11:09:26] [snowpack] └── @aws-sdk/middleware-host-header@3.170.0
[11:09:26] [snowpack] └── @aws-sdk/middleware-logger@3.170.0
[11:09:26] [snowpack] └── @aws-sdk/middleware-recursion-detection@3.170.0
[11:09:26] [snowpack] └── @aws-sdk/middleware-retry@3.170.0
[11:09:27] [snowpack]   └── @aws-sdk/service-error-classification@3.170.0
[11:09:27] [snowpack]   └── uuid@8.3.2
[11:09:27] [snowpack] └── @aws-sdk/middleware-signing@3.170.0
[11:09:27] [snowpack]   └── @aws-sdk/property-provider@3.170.0
[11:09:27] [snowpack]   └── @aws-sdk/signature-v4@3.170.0
[11:09:28] [snowpack]     └── @aws-sdk/util-hex-encoding@3.170.0
[11:09:28] [snowpack]     └── @aws-sdk/util-uri-escape@3.170.0
[11:09:28] [snowpack] └── @aws-sdk/middleware-user-agent@3.170.0
[11:09:28] [snowpack] └── @aws-crypto/sha1-browser@2.0.0
[11:09:28] [snowpack]   └── @aws-sdk/util-locate-window@3.170.0
[11:09:28] [snowpack]   └── @aws-crypto/supports-web-crypto@2.0.2
[11:09:28] [snowpack]   └── @aws-crypto/ie11-detection@2.0.2
[11:09:28] [snowpack] └── @aws-crypto/sha256-browser@2.0.0
[11:09:28] [snowpack]   └── @aws-crypto/sha256-js@2.0.0
[11:09:29] [snowpack] └── @aws-sdk/eventstream-serde-browser@3.170.0
[11:09:29] [snowpack]   └── @aws-sdk/eventstream-serde-universal@3.170.0
[11:09:29] [snowpack]     └── @aws-sdk/eventstream-codec@3.170.0
[11:09:29] [snowpack] └── @aws-sdk/fetch-http-handler@3.170.0
[11:09:29] [snowpack]   └── @aws-sdk/querystring-builder@3.170.0
[11:09:30] [snowpack]   └── @aws-sdk/util-base64-browser@3.170.0
[11:09:30] [snowpack] └── @aws-sdk/hash-blob-browser@3.170.0
[11:09:30] [snowpack]   └── @aws-sdk/chunked-blob-reader@3.170.0
[11:09:30] [snowpack] └── @aws-sdk/invalid-dependency@3.170.0
[11:09:30] [snowpack] └── @aws-sdk/md5-js@3.170.0
[11:09:30] [snowpack]   └── @aws-sdk/util-utf8-node@3.170.0
[11:09:31] [snowpack]     └── @aws-sdk/util-buffer-from@3.170.0
[11:09:31] [snowpack] └── @aws-sdk/util-body-length-browser@3.170.0
[11:09:31] [snowpack] └── @aws-sdk/util-stream-browser@3.170.0
[11:09:31] [snowpack] └── @aws-sdk/util-user-agent-browser@3.170.0
[11:09:31] [snowpack]   └── bowser@2.11.0
[11:09:32] [snowpack] └── @aws-sdk/signature-v4-multi-region@3.170.0
[11:09:32] [snowpack] └── @aws-sdk/url-parser@3.170.0
[11:09:32] [snowpack]   └── @aws-sdk/querystring-parser@3.170.0
[11:09:32] [snowpack] └── @aws-sdk/util-defaults-mode-browser@3.170.0
[11:09:32] [snowpack] └── @aws-sdk/util-waiter@3.170.0
[11:09:32] [snowpack] + @aws-sdk/lib-storage@3.170.0
[11:09:33] [snowpack] └── @aws-sdk/abort-controller@3.170.0
[11:09:33] [snowpack] └── events@3.3.0
[11:09:33] [snowpack] └── buffer@5.6.0
[11:09:33] [snowpack]   └── base64-js@1.5.1
[11:09:34] [snowpack]   └── ieee754@1.2.1
[11:09:34] [snowpack] Ready!
[11:09:34] [snowpack] Server started in 41ms.
[11:09:34] [snowpack] Local: http://localhost:8080
[11:09:34] [snowpack] Network: http://192.168.2.7:8080
[11:09:34] [@snowpack/plugin-typescript] 10:08:34 AM - Starting compilation in watch mode...
[11:09:36] [@snowpack/plugin-typescript] 10:08:36 AM - Found 0 errors. Watching for file changes.
[11:09:37] [snowpack] Chrome not responding to Snowpack after 3s. Opening in new tab.
⠼ watching for file changes.../Users/chrislu/dev/s3-multipart-error/app/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

If you're using npm v7, make sure your package-lock.json file contains either
"lockfileVersion": 1 or the code "hasInstallScript": true. If it doesn't have
either of those, then it is likely the case that a known bug in npm v7 has
corrupted your package-lock.json file. Regenerating your package-lock.json file
should fix this issue.

    at Object.<anonymous> (/Users/chrislu/dev/s3-multipart-error/app/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
[11:09:38] [snowpack] Build Result Error: There was a problem with a file build result.
[11:09:38] [snowpack] Error: The service was stopped
    at /Users/chrislu/dev/s3-multipart-error/app/node_modules/esbuild/lib/main.js:1066:33
    at /Users/chrislu/dev/s3-multipart-error/app/node_modules/esbuild/lib/main.js:568:9
    at Socket.afterClose (/Users/chrislu/dev/s3-multipart-error/app/node_modules/esbuild/lib/main.js:546:7)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  __snowpackBuildDetails: { name: '@snowpack/plugin-esbuild', step: 'load' }
}
[11:09:38] [snowpack] Error: The service was stopped
[11:09:38] [@snowpack/plugin-esbuild] [500] /dist/SeaweedUploaderS3API.js
⠴ watching for file changes...
```

**Comment by chrislusf** [comment]
no time learn this. please create a docker image to reproduce.

**Comment by jerebear12** [comment]
> no time to learn this. please create a docker image to reproduce.

We are not able to create an image for reproduction because of issues with the S3 SDK Amazon provides. We are pursuing a new fix. Thank you for your help!

**Comment by jerebear12** [comment]
@imfantuan
This is good information but not a fix for us. As you can tell by the code I provided we are using the high-level implementation of the S3 SDK. There is no way to add a list of parts or even get part information in the Upload function. All of that is handled by the SDK. We could use the [command structure](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/index.html) but I moved away from that as I found issues in that as well(no parts were being uploaded at all).

If you can think of a way for us to move towards a fix we'd love your input!

**Comment by chrislusf** [comment]
we can try to list all uploaded parts instead of specified part list.

please create a reproducible case first.
