### ISSUE TITLE
Cloud Tier - backend storage type rclone not found with v3.61

### ISSUE THREAD

**Issue by legout** [seaweedfs/seaweedfs#5185]
**Describe the bug**

I am running seaweedfs with a Cloud Tier using rclone as a storage backend according to the wiki entry [Cloud Tier](https://github.com/seaweedfs/seaweedfs/wiki/Cloud-Tier).

Since I´ve upgraded from v3.59 to v3.61, seaweed fails to start. This are the logs:

```
I0110 00:53:56.944076 master.go:269 current: 192.168.2.50:9333 peers:
I0110 00:53:56.945462 file_util.go:27 Folder /var/folders/q2/4fhm8st91rg0sh4qn4vcjz900000gn/T/ Permission: -rwx------
I0110 00:53:56.946203 file_util.go:27 Folder /var/folders/q2/4fhm8st91rg0sh4qn4vcjz900000gn/T/ Permission: -rwx------
F0110 00:53:56.946956 backend.go:55 backend storage type rclone not found
goroutine 73 [running]:
github.com/seaweedfs/seaweedfs/weed/glog.stacks(0x0)
	/github/workspace/weed/glog/glog.go:768 +0x8c
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).output(0x103885d00, 0x3, 0x140004fa620, {0x102c27cd6?, 0x1400076faa8?}, 0x1?, 0x0)
	/github/workspace/weed/glog/glog.go:719 +0x3a4
github.com/seaweedfs/seaweedfs/weed/glog.(*loggingT).printf(0x14000736d28?, 0x6?, {0x10199319f, 0x21}, {0x1400076faa8, 0x1, 0x1})
	/github/workspace/weed/glog/glog.go:657 +0xe8
github.com/seaweedfs/seaweedfs/weed/glog.Fatalf(...)
	/github/workspace/weed/glog/glog.go:1154
github.com/seaweedfs/seaweedfs/weed/storage/backend.LoadConfiguration(0x10387f160)
	/github/workspace/weed/storage/backend/backend.go:55 +0xfc
github.com/seaweedfs/seaweedfs/weed/command.startMaster({0x1400071c150, 0x1400071c168, 0x14000127a60, 0x14000127a60, 0x14000598360, 0x140006a7150, 0x1400071c170, 0x1400071c185, 0x14000598380, 0x1400071c190, ...}, ...)
	/github/workspace/weed/command/master.go:131 +0x34
created by github.com/seaweedfs/seaweedfs/weed/command.runServer in goroutine 1
	/github/workspace/weed/command/server.go:311 +0xb10
```

**System Setup**
Start command: `./weed server -s3`
Running on: Mac OSx (M1)
Seaweedfs Version: version 30GB 3.61 8ae00e47a6e3adf340cbf00269cebec2dad5ba5e darwin arm64

filer.toml
```toml
[leveldb2]
enabled = true
dir = "/data/filerldb2"
```

backend settings in master.toml
```toml
[storage.backend]
[storage.backend.rclone.default]
enabled = true
remote_name = "sbox"
key_template = "SeaweedFS/{{ slice . 0 2 }}/{{ slice . 2 4 }}/{{ slice . 4 }}" # optional
```

rclone.conf
```toml
[sbox]
type = sftp
host = u1234.your-storagebox.de
user = u1234
port = 23
pass = abc123xz
shell_type = unix
md5sum_command = md5 -r
sha1sum_command = sha1 -r

```

**Comment by kmlebedev** [comment]
https://github.com/seaweedfs/seaweedfs/commit/7a50762b9ed05f1410a24f52571b49a25cd561eb
Use full version binary without reduce size

**Comment by legout** [comment]
Thanks for the fast response.
Unfortunately, the full image is not available for arm64.

**Comment by legout** [comment]
Is there a specific reason, why the full version is only available for amd64?

**Comment by chrislusf** [comment]
need to set it up.

**Comment by DevJake** [comment]
Hey, I'm facing the same issue, although I'm running on WSL 2. Running `dpkg --print-architecture`, I get `amd64`, so hence I've tried installing and running with the following versions (all version `3.6.2`):
1. [linux_amd64](https://github.com/seaweedfs/seaweedfs/releases/download/3.62/linux_amd64.tar.gz)
2. [linux_amd64_full](https://github.com/seaweedfs/seaweedfs/releases/download/3.62/linux_amd64_full.tar.gz)
3. [linux_amd64_full_large_disk](https://github.com/seaweedfs/seaweedfs/releases/download/3.62/linux_amd64_full_large_disk.tar.gz)
4. [linux_amd64_large_disk](https://github.com/seaweedfs/seaweedfs/releases/download/3.62/linux_amd64_large_disk.tar.gz)

All of these were run with the same configuration and commands that @legout posted at the start of this thread. Each gives me the same error message of `backend storage type rclone not found`. 

Any suggestions?

---

As a side note, it doesn't seem to be made clear anywhere what all of the various binary versions are. What's the difference between the base binary, and the `full`/`large disk`/`full large disk` variants?

**Comment by chrislusf** [comment]
This should fix the build process bf0899cbf4ccb42e02f5984802d41c5e9b5e90bf

**Comment by PringlePot** [comment]
This is still not solved, there are no _full versions for arm64
