### ISSUE TITLE
[Nginx S3 proxy] Some S3 clients will fail with signature mismatch error

### ISSUE THREAD

**Issue by vikobeibe** [seaweedfs/seaweedfs#6697]
Hello,
initial observation is that S3 clients using the [jets3t toolkit](https://github.com/mondain/jets3t) (Cyberduck, S3 Mac app, etc.), or [aws4fetch](https://github.com/mhart/aws4fetch) can't list buckets contents and therefore can't upload or download files. These clients seem to expect a virtual-hosted style bucket URL by default even if they are provided with a path-style S3 endpoint. This behaviour seems to be default to various SDKs widely used in Node.js too. 
Request flow seems to be:
1. Client makes a request to connect to the S3 endpoint. If the `proxy_set_header X-Forwarded-Port $server_port;` directive is set as per the official Nginx S3 proxy template, the request fails. If the directive is commented out, the client will connect successfully, and will retrieve a list of buckets.
2. If an attempt to list bucket's contents is made, the client will switch to a virtual-hosted style request (eg. to `https://mybucket.s3.yourdomain.com` even if the endpoint was set to `https://s3.yourdomain.com`) and it will fail with a `The request signature we calculated does not match the signature you provided.` error. 

My assumption is that when switching over to virtual-hosted style requests, these clients will calculate the signature in a way that is different from the way Seaweed does. I have not been able to identify why yet. This behaviour is not present in some clients like Transmit, which seems to rely on path-style requests entirely by default. 

Reproduce:
Install weed 3.85
Apply default Nginx S3 proxy template
Create appropriate DNS records
Create a test bucket
Create user with Read,Write,List,Tagging actions, set access and secret keys, and add the user to the bucket
Attempt to connect and list buckets with Cyberduck, S3 app for Mac, or [this gist](https://github.com/mhart/aws4fetch) for aws4fetch

**Comment by zuzuviewer** [comment]
fixed with #6698

**Comment by vikobeibe** [comment]
Thank you. I’ve had more time for testing today and I believe that the signature mismatch issue remains (virtual hosted style buckets only when auth v4 is used).

Request from client using v2 auth type, set to use path-style buckets:
```
GET /5637?delimiter=%2F&list-type=2 HTTP/1.1
Host: mydomain.com
```

This request works, because client is requesting the bucket as part of the URL, and Seaweedfs is signing the request with the bucket as part of the path (in this case bucket name is `5637`). Both parties sign the same URL.

Request from a client using v4 auth type, which uses virtual-hosted style by default:
```
GET /?delimiter=%2F&list-type=2
Host: 5637.mydomain.com
```

In this case, client sends the request without the bucket name, because bucket would be derived by AWS from `$host` header. On Seaweedfs side, the bucket needs to be extracted from host, and added to the `proxy_pass` directive, which is done via a rewrite as per the Nginx template: `rewrite (.*) /$bucket$1 last;` However, now the bucket is part of the path and signature will be different.

Final URL for which the client calculates the signature: 
`https://5637.mydomain.com/?delimiter=%2F&list-type=2`
Seaweed will instead calculate for:
`https://5637.mydomain.com/5637/?delimiter=%2F&list-type=2`

I have noted the `X-Forwarded-Prefix` header that is available in `auth_signature_v4.go` , and I think that introducing a simillar header that could do the opposite, could be one option for an elegant solution. Example: 
```
if ($bucket != "") {
	proxy_set_header X-Sign-Except /$bucket/;
	rewrite (.*) /$bucket$1 last;
}
```

This shifts potential added complexity in deciding which request should be considered virtual+v4 auth type from Seaweedfs to Nginx. 
Seaweedfs could remove the value of the header for the purpose of calculations when it’s present.

Potential issues:
Tools using auth type `<` v4 `AND` defaulting to virtual-hosted style buckets may fail. I have not been able to find a tool that uses this configuration by default to test. 

Steps to reproduce:
Same as in OP. 
Easiest way to reproduce (on Mac) is with “S3 Files” app where adding or removing an ending slash to the S3 URL endpoint will result in switching between path-style and virtual-hosted style requests, both using v4 auth type.

**Comment by zuzuviewer** [comment]
Virtual-host is not supported by seaweedfs.

**Comment by quynguyenxuan** [comment]
Hi, I made it worked with virtual host style behind HAproxy

```
    acl is_s3_vhost_domain hdr(Host) -m reg ^([^.]+)\.s3-viettel\.sunteco\.cloud$

    http-request set-var(req.bucket) req.hdr(Host),field(1,.) if is_s3_vhost_domain
    http-request set-var(req.path) path if is_s3_vhost_domain
    http-request set-header X-Forwarded-Path %[var(req.path)] if is_s3_vhost_domain

    http-request set-path /%[var(req.bucket)]%[path] if is_s3_vhost_domain
    http-request set-header Host %[req.hdr(Host)] if is_s3_vhost_domain
```

Then force use X-Forwarded-Path on verify signature

```
        if xPath := r.Header.Get("X-Forwarded-Path"); xPath != "" {
		urlPath = xPath
	}
	// / Verify finally if signature is same.

	// Get canonical request.
	presignedCanonicalReq := getCanonicalRequest(extractedSignedHeaders, hashedPayload, encodedQuery, urlPath, req.Method)
```
