### ISSUE TITLE
Error in maintenance_workers.templ

### ISSUE THREAD

**Issue by CompuRoot** [seaweedfs/seaweedfs#6966]
Run on `commit 93bbaa1fb486f95ff40f5891057f8415bdf3fc27 (HEAD -> master, origin/master, origin/HEAD)`:
```
make admin-generate
```

return error [`template closing brace not found: line 285, col 102`]:
```
Generating templ files...
(✗) Error [ error=failed to generate code for ".../seaweedfs/weed/admin/view/app/maintenance_workers.templ": .../seaweedfs/weed/admin/view/app/maintenance_workers.templ parsing error: template closing brace not found: line 285, col 102 ]
(✗) Command failed: generation completed with 1 errors
```

**Comment by chrislusf** [comment]
this should have been fixed now.

**Comment by CompuRoot** [comment]
> this should have been fixed now.

```
make admin-generate
```

still throw errors on the same template and now `topics.templ` start blaming too 

```
Generating templ filesseaweedfs
(✗) Error [ error=failed to generate code for "seaweedfs/weed/admin/view/app/maintenance_workers.templ": seaweedfs/weed/admin/view/app/maintenance_workers.templ parsing error: template closing brace not found: line 285, col 102 ]
(✗) Error [ error=failed to generate code for "seaweedfs/weed/admin/view/app/topics.templ": seaweedfs/weed/admin/view/app/topics.templ parsing error: template closing brace not found: line 222, col 40 ]
(✗) Command failed: generation completed with 2 errors
```

**Comment by chrislusf** [comment]
fixed. the templ version was a bit old.
